#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmail
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gmaiil")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertcompte(compte instance);
    partial void Updatecompte(compte instance);
    partial void Deletecompte(compte instance);
    partial void Insertmsg(msg instance);
    partial void Updatemsg(msg instance);
    partial void Deletemsg(msg instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::gmail.Properties.Settings.Default.gmaiilConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<compte> compte
		{
			get
			{
				return this.GetTable<compte>();
			}
		}
		
		public System.Data.Linq.Table<msg> msg
		{
			get
			{
				return this.GetTable<msg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.compte")]
	public partial class compte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _nom;
		
		private string _prenom;
		
		private string _mdps;
		
		private string _sexe;
		
		private System.Nullable<System.DateTime> _daten;
		
		private string _qs;
		
		private string _qr;
		
		private System.Data.Linq.Binary _img;
		
		private EntitySet<msg> _msg;
		
		private EntitySet<msg> _msg1;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnmdpsChanging(string value);
    partial void OnmdpsChanged();
    partial void OnsexeChanging(string value);
    partial void OnsexeChanged();
    partial void OndatenChanging(System.Nullable<System.DateTime> value);
    partial void OndatenChanged();
    partial void OnqsChanging(string value);
    partial void OnqsChanged();
    partial void OnqrChanging(string value);
    partial void OnqrChanged();
    partial void OnimgChanging(System.Data.Linq.Binary value);
    partial void OnimgChanged();
    #endregion
		
		public compte()
		{
			this._msg = new EntitySet<msg>(new Action<msg>(this.attach_msg), new Action<msg>(this.detach_msg));
			this._msg1 = new EntitySet<msg>(new Action<msg>(this.attach_msg1), new Action<msg>(this.detach_msg1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mdps", DbType="VarChar(50)")]
		public string mdps
		{
			get
			{
				return this._mdps;
			}
			set
			{
				if ((this._mdps != value))
				{
					this.OnmdpsChanging(value);
					this.SendPropertyChanging();
					this._mdps = value;
					this.SendPropertyChanged("mdps");
					this.OnmdpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexe", DbType="VarChar(30)")]
		public string sexe
		{
			get
			{
				return this._sexe;
			}
			set
			{
				if ((this._sexe != value))
				{
					this.OnsexeChanging(value);
					this.SendPropertyChanging();
					this._sexe = value;
					this.SendPropertyChanged("sexe");
					this.OnsexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daten", DbType="DateTime")]
		public System.Nullable<System.DateTime> daten
		{
			get
			{
				return this._daten;
			}
			set
			{
				if ((this._daten != value))
				{
					this.OndatenChanging(value);
					this.SendPropertyChanging();
					this._daten = value;
					this.SendPropertyChanged("daten");
					this.OndatenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qs", DbType="VarChar(30)")]
		public string qs
		{
			get
			{
				return this._qs;
			}
			set
			{
				if ((this._qs != value))
				{
					this.OnqsChanging(value);
					this.SendPropertyChanging();
					this._qs = value;
					this.SendPropertyChanged("qs");
					this.OnqsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qr", DbType="VarChar(30)")]
		public string qr
		{
			get
			{
				return this._qr;
			}
			set
			{
				if ((this._qr != value))
				{
					this.OnqrChanging(value);
					this.SendPropertyChanging();
					this._qr = value;
					this.SendPropertyChanged("qr");
					this.OnqrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compte_msg", Storage="_msg", ThisKey="email", OtherKey="adrdes")]
		public EntitySet<msg> msg
		{
			get
			{
				return this._msg;
			}
			set
			{
				this._msg.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compte_msg1", Storage="_msg1", ThisKey="email", OtherKey="adrexp")]
		public EntitySet<msg> msg1
		{
			get
			{
				return this._msg1;
			}
			set
			{
				this._msg1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_msg(msg entity)
		{
			this.SendPropertyChanging();
			entity.compte = this;
		}
		
		private void detach_msg(msg entity)
		{
			this.SendPropertyChanging();
			entity.compte = null;
		}
		
		private void attach_msg1(msg entity)
		{
			this.SendPropertyChanging();
			entity.compte1 = this;
		}
		
		private void detach_msg1(msg entity)
		{
			this.SendPropertyChanging();
			entity.compte1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.msg")]
	public partial class msg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idm;
		
		private string _adrexp;
		
		private string _adrdes;
		
		private string _corps;
		
		private string _objet;
		
		private System.Nullable<int> _important;
		
		private System.Nullable<System.DateTime> _datemsg;
		
		private System.Nullable<int> _lu;
		
		private System.Nullable<bool> _supex;
		
		private System.Nullable<bool> _supdes;
		
		private System.Data.Linq.Binary _img;
		
		private System.Nullable<int> _important1;
		
		private System.Nullable<int> _lu1;
		
		private EntityRef<compte> _compte;
		
		private EntityRef<compte> _compte1;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidmChanging(int value);
    partial void OnidmChanged();
    partial void OnadrexpChanging(string value);
    partial void OnadrexpChanged();
    partial void OnadrdesChanging(string value);
    partial void OnadrdesChanged();
    partial void OncorpsChanging(string value);
    partial void OncorpsChanged();
    partial void OnobjetChanging(string value);
    partial void OnobjetChanged();
    partial void OnimportantChanging(System.Nullable<int> value);
    partial void OnimportantChanged();
    partial void OndatemsgChanging(System.Nullable<System.DateTime> value);
    partial void OndatemsgChanged();
    partial void OnluChanging(System.Nullable<int> value);
    partial void OnluChanged();
    partial void OnsupexChanging(System.Nullable<bool> value);
    partial void OnsupexChanged();
    partial void OnsupdesChanging(System.Nullable<bool> value);
    partial void OnsupdesChanged();
    partial void OnimgChanging(System.Data.Linq.Binary value);
    partial void OnimgChanged();
    partial void Onimportant1Changing(System.Nullable<int> value);
    partial void Onimportant1Changed();
    partial void Onlu1Changing(System.Nullable<int> value);
    partial void Onlu1Changed();
    #endregion
		
		public msg()
		{
			this._compte = default(EntityRef<compte>);
			this._compte1 = default(EntityRef<compte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idm", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idm
		{
			get
			{
				return this._idm;
			}
			set
			{
				if ((this._idm != value))
				{
					this.OnidmChanging(value);
					this.SendPropertyChanging();
					this._idm = value;
					this.SendPropertyChanged("idm");
					this.OnidmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adrexp", DbType="VarChar(50)")]
		public string adrexp
		{
			get
			{
				return this._adrexp;
			}
			set
			{
				if ((this._adrexp != value))
				{
					if (this._compte1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnadrexpChanging(value);
					this.SendPropertyChanging();
					this._adrexp = value;
					this.SendPropertyChanged("adrexp");
					this.OnadrexpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adrdes", DbType="VarChar(50)")]
		public string adrdes
		{
			get
			{
				return this._adrdes;
			}
			set
			{
				if ((this._adrdes != value))
				{
					if (this._compte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnadrdesChanging(value);
					this.SendPropertyChanging();
					this._adrdes = value;
					this.SendPropertyChanged("adrdes");
					this.OnadrdesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_corps", DbType="VarChar(30)")]
		public string corps
		{
			get
			{
				return this._corps;
			}
			set
			{
				if ((this._corps != value))
				{
					this.OncorpsChanging(value);
					this.SendPropertyChanging();
					this._corps = value;
					this.SendPropertyChanged("corps");
					this.OncorpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objet", DbType="VarChar(30)")]
		public string objet
		{
			get
			{
				return this._objet;
			}
			set
			{
				if ((this._objet != value))
				{
					this.OnobjetChanging(value);
					this.SendPropertyChanging();
					this._objet = value;
					this.SendPropertyChanged("objet");
					this.OnobjetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_important", DbType="Int")]
		public System.Nullable<int> important
		{
			get
			{
				return this._important;
			}
			set
			{
				if ((this._important != value))
				{
					this.OnimportantChanging(value);
					this.SendPropertyChanging();
					this._important = value;
					this.SendPropertyChanged("important");
					this.OnimportantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datemsg", DbType="DateTime")]
		public System.Nullable<System.DateTime> datemsg
		{
			get
			{
				return this._datemsg;
			}
			set
			{
				if ((this._datemsg != value))
				{
					this.OndatemsgChanging(value);
					this.SendPropertyChanging();
					this._datemsg = value;
					this.SendPropertyChanged("datemsg");
					this.OndatemsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lu", DbType="Int")]
		public System.Nullable<int> lu
		{
			get
			{
				return this._lu;
			}
			set
			{
				if ((this._lu != value))
				{
					this.OnluChanging(value);
					this.SendPropertyChanging();
					this._lu = value;
					this.SendPropertyChanged("lu");
					this.OnluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supex", DbType="Bit")]
		public System.Nullable<bool> supex
		{
			get
			{
				return this._supex;
			}
			set
			{
				if ((this._supex != value))
				{
					this.OnsupexChanging(value);
					this.SendPropertyChanging();
					this._supex = value;
					this.SendPropertyChanged("supex");
					this.OnsupexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supdes", DbType="Bit")]
		public System.Nullable<bool> supdes
		{
			get
			{
				return this._supdes;
			}
			set
			{
				if ((this._supdes != value))
				{
					this.OnsupdesChanging(value);
					this.SendPropertyChanging();
					this._supdes = value;
					this.SendPropertyChanged("supdes");
					this.OnsupdesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_important1", DbType="Int")]
		public System.Nullable<int> important1
		{
			get
			{
				return this._important1;
			}
			set
			{
				if ((this._important1 != value))
				{
					this.Onimportant1Changing(value);
					this.SendPropertyChanging();
					this._important1 = value;
					this.SendPropertyChanged("important1");
					this.Onimportant1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lu1", DbType="Int")]
		public System.Nullable<int> lu1
		{
			get
			{
				return this._lu1;
			}
			set
			{
				if ((this._lu1 != value))
				{
					this.Onlu1Changing(value);
					this.SendPropertyChanging();
					this._lu1 = value;
					this.SendPropertyChanged("lu1");
					this.Onlu1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compte_msg", Storage="_compte", ThisKey="adrdes", OtherKey="email", IsForeignKey=true)]
		public compte compte
		{
			get
			{
				return this._compte.Entity;
			}
			set
			{
				compte previousValue = this._compte.Entity;
				if (((previousValue != value) 
							|| (this._compte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._compte.Entity = null;
						previousValue.msg.Remove(this);
					}
					this._compte.Entity = value;
					if ((value != null))
					{
						value.msg.Add(this);
						this._adrdes = value.email;
					}
					else
					{
						this._adrdes = default(string);
					}
					this.SendPropertyChanged("compte");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compte_msg1", Storage="_compte1", ThisKey="adrexp", OtherKey="email", IsForeignKey=true)]
		public compte compte1
		{
			get
			{
				return this._compte1.Entity;
			}
			set
			{
				compte previousValue = this._compte1.Entity;
				if (((previousValue != value) 
							|| (this._compte1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._compte1.Entity = null;
						previousValue.msg1.Remove(this);
					}
					this._compte1.Entity = value;
					if ((value != null))
					{
						value.msg1.Add(this);
						this._adrexp = value.email;
					}
					else
					{
						this._adrexp = default(string);
					}
					this.SendPropertyChanged("compte1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
